ssoServiceUrl: http://localhost:8080
server:
  port: 8081
spring:
  thymeleaf:
    cache: false
security:
  ignored: /favicon.ico, /
  basic:
    enabled: false
  oauth2:
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
      user-info-uri: http://localhost:8080/me

logging.level:
  org.springframework.security: DEBUG